### ISSUE TITLE
causalgraphicalmodels import error with Python 3.10

### ISSUE THREAD

**Issue by EAly** [pymc-devs/pymc-resources#200]
running ```from causalgraphicalmodels import CausalGraphicalModels``` on Python 3.10 results in the following error:

```
ImportError: cannot import name 'Iterable' from 'collections'
```
In Python > 3.9 ```iterable``` should be imported from ```collections.abc```

so any idea for how to get ```causalgraphicalmodels``` to run on Python 3.10?

**Comment by canyon289** [comment]
Hey @EAly,
This seems like an issue with CausalGraphicalModels and not PyMC? Just to be specific what is it you would like the PyMC team to help with?

**Comment by EAly** [comment]
Thanks for your reply @canyon289 ,

I know this is an issue with causalgraphicalmodels, I was just wondering if you can provide any advice or workaround on how to handle this problem.

**Comment by canyon289** [comment]
Sure thing!
Simplest would be to downgrade the version of python to 3.9, then everything should work. That or see if upgrading the version of causallgraphicmodels to see if it supports 3.10

One question, when installing this environment did you the environment file associated with the resource youre trying to use? That should help you avoid these issues

**Comment by EAly** [comment]
I did the python 3.9 thing and it is working fine now. I didn't stick to the environment file associated with the resource as I wanted to use pymc4.

Thanks again for your reply and help. I would also appreciate it the most if you can take a look at this [issue](https://github.com/pymc-devs/pymc-resources/issues/199) 😃

**Comment by canyon289** [comment]
Great, I'll go ahead and close this.

One tip, when opening issues for OSS projects its good to include the code youre running, in this case a link to the notebook, and all the versions of major packages and python. Ideally with a small reproducible example. without that its impossible for us to help you.

Glad you got it figured out!
