### ISSUE TITLE
Outline of Rethinking2 chapters

### ISSUE THREAD

**Issue by AlexAndorra** [pymc-devs/pymc-resources#67]
As discussed with @aloctavodia, here is an outline of chapters we're porting to PyMC3 for _Rethinking_ 2. This way we can keep track of where we are -- let's **comment** below **when we start** porting a new chapter, and **check the box when the chapter is merged**.

- [x] Chapter 2 -- Small Worlds and Large Worlds
- [x] Chapter 3 -- Sampling the Imaginary
- [x] Chapter 4 -- Geocentric Models
- [x] Chapter 5 -- The Many Variables & The Spurious Waffles
- [x] Chapter 6 -- The Haunted DAG & The Causal Terror
- [x] Chapter 7 -- Ulysses' Compass (@oscarbranson)
- [x] Chapter 8 -- Conditional Manatees (@oscarbranson)
- [x] Chapter 9 -- Markov Chain Monte Carlo (@nilichen)
- [x] Chapter 10 -- Big Entropy and the Generalized Linear Model (@nilichen)
- [x] Chapter 11 -- God Spiked the Integers
- [x] Chapter 12 -- Monsters and Mixtures
- [x] Chapter 13 -- Models with Memory (@AlexAndorra)
- [x] Chapter 14 -- Adventures in Covariance (@AlexAndorra)
- [ ] Chapter 15 -- Missing Data and Other Opportunities (**open to claim**)
- [ ] Chapter 16 -- Generalized Linear Madness (**open to claim**)

**Comment by aloctavodia** [comment]
I will work on Chapter 7 -- Ulysses' Compass

**Comment by canyon289** [comment]
Claiming Chapter 5 and 6

**Comment by AlexAndorra** [comment]
Perfect, I'm gonna work on chapters 11 through 15!

Le lun. 20 janv. 2020 à 06:44, Ravin Kumar <notifications@github.com> a
écrit :

**Comment by nilichen** [comment]
I’d like to work on the rest 8-10.

**Comment by AlexAndorra** [comment]
Hi Katrina,
I think these chapters are indeed available, so thanks for your help! And don't hesitate to ask us should you have any questions :)

I also checked the box of merged/ready-to-merge chapters above 👌 
Continuing my journey with chapter 13 🎉

**Comment by canyon289** [comment]
Hi, I'll take 15 and 16!

**Comment by canyon289** [comment]
@nilichen Welcome! I added your handle to those chapters to indicate they've been claimed by you. Welcome to the community and thanks for the contributions!

**Comment by oscarbranson** [comment]
Hi folks. I'm the egit that just submitted a PR for Chapter 6 without noticing this thread... 

I'm happy to contribute more, but it looks like they're all spoken for... want to throw any my way? Preference for 7-10, as that's the stage I'm at in the book. Can I take one off your hands, @nilichen?

**Comment by aloctavodia** [comment]
@oscarbranson do you want to work on chapter 7? I was supposed to work on that, but I will not have the time for the moment. So, if you want to work on that I will be happy to review your PR, or help if you find some problem.

**Comment by oscarbranson** [comment]
Sure thing @aloctavodia. That's actually perfect - I'm working my way through the book and chapter 7 is up next!

Should have a PR up in the next day or two.

**Comment by oscarbranson** [comment]
I'm in the process of going through Chapter 8 for my own purposes... mind if I set up a PR, @nilichen?

**Comment by nilichen** [comment]
Sure go ahead please. Thanks!

**Comment by oscarbranson** [comment]
Chapter 8 ready for review (#88)!

**Comment by oscarbranson** [comment]
Similarly Chapter 9, @nilichen? I'm going through it today anyway...

**Comment by oscarbranson** [comment]
In case it lost in the confusion of my messed up PR, and in case anyone has time to review it, Chapter 9 is now ready for review on #91!

**Comment by AlexAndorra** [comment]
Hi @oscarbranson! Thanks for your work and for the heads-up, and sorry for not replying earlier -- we're all being a bit swamped these days 😩 
@aloctavodia will try to review your PR this week, and if he can't I'll try to do it 😉

**Comment by aloctavodia** [comment]
I will work on Chapter 10.

**Comment by ricardoV94** [comment]
I have implemented a working version of the "16.2. Hidden minds and observed behavior" model if it is still needed. I am not interested in the rest of the chapter, so I wouldn't "claim it entirely".

**Comment by canyon289** [comment]
@ricardoV94 Feel free to open a PR adding just that and I can modify the header of this issue to indicate 16.2 is partially compelted!

**Comment by michaeloriordan** [comment]
Hi all, I'm nearly finished working my way through chapter 15 and would be happy to open a PR when I'm done, if this is needed?

**Comment by AlexAndorra** [comment]
@michaeloriordan , that'd be more than welcome! Looking forward to your PR then, and let us know if you have questions 😉

**Comment by fonnesbeck** [comment]
Last two chapters appear to have been merged.
