### ISSUE TITLE
Implementing exercise 6.3.3 of Bayesian Cognitive Modeling

### ISSUE THREAD

**Issue by drussellmrichie** [pymc-devs/pymc-resources#74]
Thanks for providing the pymc3 code to this book. It's been a lot of fun going through it!

I'm trying to modify the code to the twenty questions model to use the Rasch model of question accuracy for exercise 6.3.3, but I'm not sure how to do this, and googling has been little help. It seems like something like this should be possible....

```
with pm.Model() as model3:
    # prior
    pi = pm.Beta('pi', alpha=1, beta=1, shape=Np)
    qj = pm.Beta('qj', alpha=1, beta=1, shape=Nq)
    # accuracy prior
#     theta = pm.Deterministic('theta', tt.outer(pi, qj))
    pi_min_qj = tt.sub.outer(pi, qj)
    theta = pm.Deterministic('theta', tt.exp(pi_min_qj) / (1+tt.exp(pi_min_qj)))
    # observed
    kij = pm.Bernoulli('kij', p=theta, observed=k)
    
    trace3=pm.sample(3000, tune=1000)
```

But of course there is no tt.sub.outer. Any help is much appreciated.

EDIT:
Actually, I think this does the trick?
```
with pm.Model() as model3:
    # prior

    pi = pm.Beta('pi', alpha=1, beta=1, shape=(Np, 1))
    qj = pm.Beta('qj', alpha=1, beta=1, shape=(1, Nq))

    # accuracy prior
    theta = pm.Deterministic('theta', tt.exp(pi-qj) / (1+tt.exp(pi-qj)))
    
    # observed
    kij = pm.Bernoulli('kij', p=theta, observed=k)
    
    trace3=pm.sample(3000, tune=1000)
```

**Comment by hkoohy** [comment]
thank you, I had the same question, your solution helps getting the code work, thank you for that.
Thought the posterior for qj from Rasch model is not consistent with the first simple model and actually deosnt make sense.For example Q5 has not been answered by any person yet gets very high posterior!
I wonder you also get the same figure?
![Screenshot 2020-06-07 at 09 34 53](https://user-images.githubusercontent.com/30291080/83964079-2f4d8800-a8a2-11ea-847d-b21593bb5d86.png)

**Comment by drussellmrichie** [comment]
Hi, it's been a little while since I thought about this dataset, but I think in the Rasch model qj is question difficulty, not ease (as it is in section 6.3 of the text). So I think a high posterior for question 5 makes sense. And that's why question 10 (question J), which 6/10 people got right (the highest rate of any question) has a low posterior.

**Comment by fonnesbeck** [comment]
Closed due to inactivity.
